language: node_js
node_js: lts/*
install:
- npm install
script:
- npm run docs
- git checkout --track origin/gh-pages
- rm -f -r docs
- rm -f -r gitbook
- rm index.html
- rm search_index.json
- cp -R _book/* .
- git add -A
- git commit -m "Travis CI update"
